services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: mydatabase
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  gilhari:
    build: .
    ports:
      - "80:8081"
    depends_on:
      - postgres

volumes:
  postgres_data: